services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GallardoLP-570
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: SILLICON_STORE
      MYSQL_RANDOM_ROOT_PASSWORD: false
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./sillicon_store_dump.sql:/docker-entrypoint-initdb.d/sillicon_store_dump.sql
    command: ["--log-bin-trust-function-creators"]