version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: SILLICON_STORE
      MYSQL_RANDOM_ROOT_PASSWORD: false
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql